jobs:
  build-relay:
    name: 构建中继服务程序
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - name: 构建
        run: cargo build -p pupu-relay --release
      - name: 上传构建产物
        uses: actions/upload-artifact@v6
        with:
          path: target/release/pupu-relay
