/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WindowRouteImport } from './routes/window'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WindowLoginRouteImport } from './routes/window/login'
import { Route as WindowChatRouteImport } from './routes/window/chat'

const WindowRoute = WindowRouteImport.update({
  id: '/window',
  path: '/window',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowLoginRoute = WindowLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => WindowRoute,
} as any)
const WindowChatRoute = WindowChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => WindowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/window': typeof WindowRouteWithChildren
  '/window/chat': typeof WindowChatRoute
  '/window/login': typeof WindowLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/window': typeof WindowRouteWithChildren
  '/window/chat': typeof WindowChatRoute
  '/window/login': typeof WindowLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/window': typeof WindowRouteWithChildren
  '/window/chat': typeof WindowChatRoute
  '/window/login': typeof WindowLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/window' | '/window/chat' | '/window/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/window' | '/window/chat' | '/window/login'
  id: '__root__' | '/' | '/window' | '/window/chat' | '/window/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WindowRoute: typeof WindowRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/window': {
      id: '/window'
      path: '/window'
      fullPath: '/window'
      preLoaderRoute: typeof WindowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/login': {
      id: '/window/login'
      path: '/login'
      fullPath: '/window/login'
      preLoaderRoute: typeof WindowLoginRouteImport
      parentRoute: typeof WindowRoute
    }
    '/window/chat': {
      id: '/window/chat'
      path: '/chat'
      fullPath: '/window/chat'
      preLoaderRoute: typeof WindowChatRouteImport
      parentRoute: typeof WindowRoute
    }
  }
}

interface WindowRouteChildren {
  WindowChatRoute: typeof WindowChatRoute
  WindowLoginRoute: typeof WindowLoginRoute
}

const WindowRouteChildren: WindowRouteChildren = {
  WindowChatRoute: WindowChatRoute,
  WindowLoginRoute: WindowLoginRoute,
}

const WindowRouteWithChildren =
  WindowRoute._addFileChildren(WindowRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WindowRoute: WindowRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
